### ISSUE TITLE
Update of oauthlib to >=3.0.1 breaks geonode-2.10-rc4

### ISSUE THREAD

**Issue by martinwilkerson-scisys** [GeoNode/geonode-oauth-toolkit#3]
In commit f32211e492ec1afaa5e0b1d3e0549d7758179126, the required version of oauthlib was bumped to >=3.0.1. Unfortunately, GeoNode 2.10-rc4 pulls in geonode-auth-toolkit with a >= version match, so this new version is now being installed while oauthlib==2.1.0 is still being installed by other packages in the GeoNode dependency tree, and it's ignoring the pre-release flag for some reason. This breaks when e.g. doing collectstatic, as oauthlib 2.1.0 is installed and geonode-oauth-toolkit tries to load >=3.0.1.

Not certain that this is an issue for this project, as a) pip shouldn't be pulling in the pre-release package, b) GeoNode should be specifying the version more closely perhaps, and c) this can be worked around by adding geonode-oauth-toolkit==1.1.3 to our requirements.txt (or the geonode one), but it's a change in this project that has broken our existing, working, deployment of geonode.

**Comment by afabiani** [comment]
@martinwilkerson-scisys thanks for your feedback. I'll try to have a look at this.

In the meantime, I've removed the alpha versions from pypi. Could you maybe try again? Can you confirm that the requirements fetching from Pypi? I'm asking this because in theory "pip" shouldn't be able to fetch the pre-release packages unless explicitly specified.

**Comment by cesarbenjamindotnet** [comment]
is this still relevant?
